### PR TITLE
Add PureConfig;

### PR DESCRIPTION
**Pull request by Samehadar**

### CODE REVIEW

**Review by DoSOfRedRiver — APPROVED** [review]
Ladno, tolo ot'ebis!

**Comment by DoSOfRedRiver** [comment]
Big up donny!!

**Comment by Samehadar** [comment]
I have received new feedback that pureconfig is govno...

**Comment by acrossoffwest** [comment]
Why did you add "govno" in to your application?

**Comment by Samehadar** [comment]
Coz I can...

**Pull request merged**
